# Generated by Django 5.1.2 on 2024-10-24 03:41

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('employee', 'Employee')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('satker', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('nip', models.CharField(max_length=18)),
                ('phone', models.CharField(max_length=15)),
                ('is_trained', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='app_employe_usernam_7abb0e_idx'), models.Index(fields=['role'], name='app_employe_role_d673c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=app.models.employee_photo_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
